trigger:
  branches:
    include:
    - main
variables:
- name: artifactName
  value: 'java-artifact'
- name: artifactPath
  value: '$(Build.ArtifactStagingDirectory)'
- name: storageAccount
  value: 'gnareshstorage'
- name: containerName
  value: 'gncontainer1'
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
    - task: CmdLine@2
      displayName: 'List Files in Amazon-Core/Target Directory'
      inputs:
        script: |
          echo "Listing contents of Amazon-Core/target directory..."
          ls -al $(System.DefaultWorkingDirectory)/Amazon-Core/target
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/Amazon-Core/target'
        Contents: '**/*.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: '$(artifactName)'
        publishLocation: 'Container'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'gnconn'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Uploading artifact to Azure Blob Storage..."
          az storage blob upload-batch \
            --account-name $(storageAccount) \
            --destination $(containerName) \
            --source $(artifactPath) \
            --auth-mode login
      displayName: 'Upload Artifact to Azure Blob Storage'

